title: My development tools notes

author: Cristian Bourceanu

navbar-link:
  About Me: "aboutme"
  Resources:
    - Config Jekyll: https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml

theme: minima
